# @see https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
---

allow-uncaught: false
async-only: false
bail: false
check-leaks: true
color: true
delay: false
diff: true
exclude:
  - /path/to/some/excluded/file
exit: false
extension:
  - js
# fgrep and grep are mutually exclusive
# fgrep: something
file:
  - test/helper
forbid-only: false
forbid-pending: false
full-trace: true
# global:
#   - $  # sample - global vars
# fgrep and grep are mutually exclusive
# grep: something
growl: false
inline-diffs: false
# needs to be used with grep or fgrep
# invert: false
package: './package.json'
recursive: true
reporter: spec
# reporter-option:
#   - foo=bar
#   - baz=quux
require:
  - '@babel/register'
  - test/setup
retries: 1
slow: 75
sort: false
# XXX: we're not using the positional arguments, since package.json scripts already define it for 'test:all'
# spec: test/**/*.spec.js     # the positional arguments!
# v8-stack-trace-limit: 100   # V8 flags are prepended with "v8-"
timeout: false
trace-warnings: true        # node flags ok
ui: bdd
watch: false
